### ISSUE TITLE
When use your player in P2PTunnel, I have some problem.

### ISSUE THREAD

**Issue by HiddenStar0412** [tcking/GiraffePlayer2#1]
I think your player is the best and I am making a player with your code.
But I have a significant problem now.
when i play the hls video in common situation, it has no problem.
But my app have a playing function in p2ptunnel. at that time, your player cannot play the video and show the errors as follows.

```
09-20 19:10:59.756 17084-17808/com.garapon.tvapp E/IJKMEDIA: http://127.0.0.1:63080/gapi/v4/Program/?gtvsession=fb199b1aebc77463131c019a1caf79e9&service_type=1&starttime=1505750340&endtime=1505752140&action=m3u8&tsid10=32738: End of file
09-20 19:10:59.756 17084-17808/com.garapon.tvapp I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [17808]
09-20 19:10:59.777 17084-17084/com.garapon.tvapp E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

```

Would you tell me the reason why "End of file" error happens?
Of course, p2p tunnel communication is a little slower than common http.
Can i set the delay time for loading?

I'll appreciate your help.

**Comment by tcking** [comment]
there are something wrong with your local media server, can VLC play the url?
is `delay time` mean timeout ?

**Comment by HiddenStar0412** [comment]
yeah, there is no problem in vlc player.
delay time i mean is the time that player wait for loading stream data, i guess.

**Comment by HiddenStar0412** [comment]
I am a stranger in development of NDK/JNI. so I cannot know the problem in internal library.

**Comment by HiddenStar0412** [comment]
In p2p tunnel, I can download the video stream file with the url.
but i cannnot play it with your player.
In other player like android videoview, exooplayer, i can play the same video in same situation.

**Comment by HiddenStar0412** [comment]
other players can not play my video smoothly. Only your player can play my videos smoothly.
But it shows errors above mentioned in p2p environment.

**Comment by tcking** [comment]
1.update to 0.1.2
2.try setOptions:
` videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1L))`

**Comment by HiddenStar0412** [comment]
I did as you said but the result is the same as before. Is there any way to play HLS video? Which part of your player is  different with other player in HLS?

**Comment by HiddenStar0412** [comment]
Excuse me, If you help me, I'll appreciate you. Your player is good player has excellent advantage, but it has only one problem other players don't have. Why does "End of file" error occur?
Thank you.

**Comment by tcking** [comment]
can u give a url that I can test?

**Comment by HiddenStar0412** [comment]
In fact, I am testing now under P2P tunnel communication environment. so I set video url as the localhost url but real video is in remote server. I guess, you cannot test. If i send demo project, would you help me with it?

**Comment by tcking** [comment]
how can i build local server as your environment,is the demo include the server?

**Comment by HiddenStar0412** [comment]
You don't need to build the server. with demo project, u can log in server under p2p tunnel. so you can play the video.
Thank you.

**Comment by tcking** [comment]
U can give me the demo and I will have a try

**Comment by HiddenStar0412** [comment]
Thank you very much!! I will make the demo project. Thanks. Wait for me.

**Comment by GaoZhenXing** [comment]
http://hehe.heheedu.com/uploadFiles/resources/2017/09/14/0f2eaba594f845ebad9bd5305bcecbec.mp4
你好，您帮我试一下这个，我在web可以打开 ，在GiraffePlayer 无法播放

**Comment by tcking** [comment]
这个视频用ijkplayer和系统的播放器都出错了，但是用exoplayer可以正常打开，建议你先在ijkplayer上提一个issue，可能是和服务器的一些行为有关，从Charles看exoplayer进行播放的时候进行了多次请求，目前还不能确定如何解决

**Comment by HiddenStar0412** [comment]
Hi, very sorry to be late. Thank you for your kindness.
I did not resolve my problem yet. So I prepared the demo app for you. For any sake, please help me.
This url is my video player demo app.
https://www.dropbox.com/s/j56sbu6lplzw7x5/TVPlayerDemo_9_27.zip?dl=0

Please, help me.

**Comment by tcking** [comment]
the final uri is like:`https://p2plocal.device.garapon.jp:63080/gapi/v4/Program/?gtvsession=3a0932893f3af0c8fa1503f04efeda16&service_type=1&starttime=1506585240&endtime=1506588300&action=m3u8&tsid10=32742` and the sever close the connection，is your server need some authorization information like some header?

**Comment by HiddenStar0412** [comment]
what does it mean? you can not  connect the server? you can not play in the android native player, too?

**Comment by tcking** [comment]
native player can play about 3s and then get error.
according to the log，when ijkplayer try get access the url get error:'end of file',and using the browser to access the url get the error 'connection refused' ,is there some log from the server?

**Comment by HiddenStar0412** [comment]
In server, there is no such log.
In demo, user access to server via P2p tunnel now. but when user login via common http protocol, your player plays the video without any problem. P2p tunel is a little slower than common situation. What problem do you think?

**Comment by tcking** [comment]
Use persistent connections  will solve the problem，just  set  `multiple_requests` to 1

in your demo is:
```
mProgramPlayer.setVideoPath(strVideoUrl);

//add this code in your playVideo function body
mProgramPlayer.getVideoInfo()
                .addOption((Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1L)))
                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "multiple_requests", 1L));

mProgramPlayer.getPlayer().start();
```

**Comment by tcking** [comment]
multiple_requests:Use persistent connections if set to 1, default is 0, there is the doc : http://ffmpeg.org/ffmpeg-protocols.html#http

**Comment by HiddenStar0412** [comment]
Thank you very very 100 times much. You excellent. This works now. Thanks.

**Comment by HiddenStar0412** [comment]
Hi, I faced the new problem now.
I am playing the living video with your player. 
so I wrote the code as follows

`        mProgramPlayer.setVideoPath(strVideoUrl);

        mProgramPlayer.getVideoInfo()
                .addOption((Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1L)))
                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "multiple_requests", 1L))
                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect_at_eof", 1L))
                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect_streamed", 1L));

        mProgramPlayer.getPlayer().start();
`

It plays for about 30 seconds ~ 1 mins without error, but OnComplete message occurs after that.

`10-12 16:41:24.894 11992-12718/com.gpn.demo E/IJKMEDIA: TYPE_FIL: Input buffer exhausted before END element found
10-12 16:41:26.573 11992-12450/com.gpn.demo D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_COMPLETED
10-12 16:41:26.573 11992-12450/com.gpn.demo D/IJKMEDIA: FFP_MSG_COMPLETED:
10-12 16:44:48.978 11992-12443/com.gpn.demo D/IJKMEDIA: ijkmp_pause()
10-12 16:44:48.978 11992-12443/com.gpn.demo D/IJKMEDIA: ijkmp_pause()=0
10-12 16:44:48.979 11992-12450/com.gpn.demo D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_PAUSE
`

What wrong with it? How do you think about it? Why Input buffer exhausted before End element found?
Thanks.

**Comment by tcking** [comment]
try to add this option:
`.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1L))`

**Comment by HiddenStar0412** [comment]
Hi, friend
I added the option as you said.  but the result is the same as old. Are there another way else? Please, help me.

**Comment by tcking** [comment]
I play the first video in you demo app about 15mins,everything goes well,is the error occur every time or every video？

**Comment by HiddenStar0412** [comment]
That was the video recorded already. I send the current source. this is the app to play live video.
https://www.dropbox.com/s/3ut2ifenc259xs4/TVPlayerDemo.7z?dl=0

**Comment by HiddenStar0412** [comment]
The error occurs every time.

**Comment by HiddenStar0412** [comment]
Please, help me, friend.

**Comment by tcking** [comment]
i can't download the demo from dropbox,aways error,can u give the live video url?

**Comment by HiddenStar0412** [comment]
This is mega url.
https://mega.nz/#!L51XlByA!gWw6D-IiCoA18Q2_5p-RJEm6n_RY-KkWLbFfbh3aiOA
please, help me.

**Comment by tcking** [comment]
demo always alert: Connect Error (TV Terminal Connect Error) that can't start playing,u can try this option:`.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "infbuf", 1L))`,but i am not sure that can work

**Comment by tcking** [comment]
the log always said: java.net.ConnectException: Connection refused

**Comment by HiddenStar0412** [comment]
I am afraid It also doesn't work. "Connection refused" error occurs sometimes by server. It works usually and now. 
Anyway, why do you think about? which is different between yours and other?

**Comment by HiddenStar0412** [comment]
I tried a lot of ways.
`                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"max-buffer-size", 164462L))
`

`                .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_PLAYER,"packet-buffering",0L))
`

`.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "timeout", 10000000L))`

But Any of them don't work. Oh, Please, help me. I guess, it is not big issue and you can do it.

**Comment by tcking** [comment]
there are something wrong with the header:Connection: close.I found that the header changed `Connection: keep-alive` to `Connection: close`,and that your server will refuse the client's requests,but I don't know why the header have been changed,I have create a issue in project ijkplayer [multiple_requests changed after a few seconds](https://github.com/Bilibili/ijkplayer/issues/3668). according to ffmpeg `http.c` u can set `header` to custom request headers,the code like that:
`.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "Connection: keep-alive\r\n"))`
after set this option,your demo playing live video about five mins without errors,just try it.

**Comment by HiddenStar0412** [comment]
Great!! you Chinese are the best!! i guess it woks now.  thank you very much.

**Comment by mdaslamHossin** [comment]
IJKMEDIA: http url  Immediate exit requested

**Comment by jmimohsin** [comment]
Hi,

I am using Lazy one library and trying to play this url http://125.17.129.8/PLTV/88888888/224/3221225942/index.m3u8

which is redirecting and playing after multiple url changes with multiple resolution support in web player.

like this;-
http://125.17.129.14/wh7f454c46tw1586235505_1470398092/PLTV/88888888/224/3221225942/01.m3u8
http://125.17.129.14/wh7f454c46tw1586235505_1470398092/PLTV/88888888/224/3221225942/02.m3u8

I am unable to play this and this is also not working in VLC Player Deskop version.
