### ISSUE TITLE
I have problems with ijkmediaplayer error (-10000,0)

### ISSUE THREAD

**Issue by Top-Pattarapol** [tcking/GiraffePlayer2#10]
I have added the compile 'com.github.tcking: ijkplayer-x86: 0.8.4' but I can not play the file on the x86 cpu.But another cpu can play normally.

I do not know what caused the problem ijkmediaplayer error (-10000,0).

Please help,Thank You

**Comment by tcking** [comment]
-10000 can't get useful information，can you give the url that i can have a try?

**Comment by Top-Pattarapol** [comment]
I use the link: http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8 in the test.

The app I made was able to play this file with other devices except x86. I do not know if it's relevant or not. Previously, this x86 machine can still play.

![screen shot 2017-11-09 at 10 40 02 am](https://user-images.githubusercontent.com/32920884/32587822-353b94fa-c53d-11e7-8254-b264ac2ccca1.png)

**Comment by tcking** [comment]
I have no x86 devices  use emulator instead and it goes well

**Comment by Top-Pattarapol** [comment]
I can already use it by switching to compile 'com.github.tcking: ijkplayer-x86: 0.8.4-full'
