### ISSUE TITLE
Add ability to choose starting time

### ISSUE THREAD

**Issue by charles-bond-metaps** [tcking/GiraffePlayer2#108]
Videos passed in could use the ability to be sent in with a specific starting second.

Something like the following would be super helpful:
VideoInfo.java -> Add "startingSeconds" (getStartingSeconds()/setStartingSeconds())

GiraffePlayer.java -> GiraffePlayer(<constructor>) -> startPosition = videoInfo.getStartingSeconds()

**Comment by tcking** [comment]
will add next version
