### ISSUE TITLE
请问这项目是不是不支持 rtsp（ijkpalyer未编译 支持rtsp格式）

### ISSUE THREAD

**Issue by MeowStone** [tcking/GiraffePlayer2#111]
videoview显示 something error
贴上报错信息：
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [24310] didn't call SDL_JNI_DetachThreadEnv() explicity
E/IJKMEDIA: rtsp://218.204.223.237:554/live/1/6D1E43167B3A7BDA/oby9efo80duh9bjf.sdp: Protocol not found
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by tcking** [comment]
试试 ` compile 'com.github.tcking:giraffeplayer2:0.1.19-full'`
