### ISSUE TITLE
Pan and Zoom on video view

### ISSUE THREAD

**Issue by frankhaykku** [tcking/GiraffePlayer2#13]
Is it possible to add a pan'n'zoom gesture to video view ?

**Comment by UbuntuLover** [comment]
yeah. I also want this feature in my app. Did you have any suggestions?

**Comment by tcking** [comment]
there is a project have this feature : https://github.com/Shuhrat-java/PanZoomPlayer , you can reference this project.
what kinds of app need this feature? video surveillance？

**Comment by UbuntuLover** [comment]
yes.Like sometimes the clients want to see some details about their home. BTW, when will the floating view feature will be released?

**Comment by frankhaykku** [comment]
Thx for your response. Did it with your example and it reduce less memory as my implementation that I did yesterday. The app is a view/control a home IP cameras. Zoom and Pannig more the optional feature than the important one. The last question to you, tcking, is it impossible to make a multiview ? On the previous version, I collect all players in RecyclerView and play them at same time. But with this version we can play only one instance and I understand why you done this,

**Comment by tcking** [comment]
@UbuntuLover a little busy recently, maybe 2 weeks later
@frankhaykku because decode video stream may be using hardware resources，so most case it can only one player active in a time.

**Comment by tcking** [comment]
@UbuntuLover float window support at version `0.1.11`

**Comment by UbuntuLover** [comment]
@tcking thanks a lot. I will try these new features and learn this player. Always,thanks a lot.(大哥真牛逼)

**Comment by UbuntuLover** [comment]
大哥还更新吗

**Comment by tcking** [comment]
短期内不会实现此feature
