### ISSUE TITLE
Ijk Media issue while loading dailymotion downloadable url

### ISSUE THREAD

**Issue by subhantariq33** [tcking/GiraffePlayer2#142]
12-14 18:43:06.727 22701-23064/com.hithot.video.streaming.all.video.downloader E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [23064] didn't call SDL_JNI_DetachThreadEnv() explicity
12-14 18:43:08.467 22701-23091/com.hithot.video.streaming.all.video.downloader E/IJKMEDIA: https://www.dailymotion.com/cdn/H264-176x144-2/video/x6k6d38.mp4?sec=or7o2ipi-4oc9HnWiz9pgr8keaoPLv5NOdKzL-_w309UThFJpiuq1N1TExi-zMsp: Server returned 403 Forbidden (access denied)
12-14 18:43:08.467 22701-22701/com.hithot.video.streaming.all.video.downloader E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by tcking** [comment]
this is because the server need authorization
