### ISSUE TITLE
Change in Orientation restarts video

### ISSUE THREAD

**Issue by TechyM** [tcking/GiraffePlayer2#144]
Every time I change orientation, video restarts from beginning. Actually it should continue itself.

 Also It doesn't go to full screen directly from portrait mode, first it changes to landscape in small screen and then goes to full screen in landscape mode. 

[OrientationIssueVideo.zip](https://github.com/tcking/GiraffePlayer2/files/2689218/OrientationIssueVideo.zip)

**Comment by tcking** [comment]
1.you activity should handle orientation change,in manifast make sure have this config for your activity `android:configChanges="keyboardHidden|orientation|screenSize"`
2.override the `onConfigurationChanged` on your activity:

```
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        PlayerManager.getInstance().onConfigurationChanged(newConfig);
    }
```

**Comment by TechyM** [comment]
thank you, it works properly now!
