### ISSUE TITLE
How to load advertisement video by pausing main video?

### ISSUE THREAD

**Issue by tusharuit25** [tcking/GiraffePlayer2#150]
I want to use this player in my app but what if i have to play my own custom ads while pausing main video? How to do this !!!

**Comment by tcking** [comment]
try create 2 player in your xml,play ad when pausing main video (by call `videoView.setPlayerListener(playerListener)` to listener the main video status)

**Comment by tcking** [comment]
the will be ok,only one player is working at a time

**Comment by tusharuit25** [comment]
Ok fits for my requirements then... ;-)
