### ISSUE TITLE
How to add User Agent and Referer both in a single player?

### ISSUE THREAD

**Issue by techcalibrator** [tcking/GiraffePlayer2#152]
`VideoInfo videoInfo = new VideoInfo(Uri.parse(swiftUrl))
                    .setTitle(channelsList.get(result).getChannelName())//config title
                    .setAspectRatio(VideoInfo.AR_MATCH_PARENT)
                    .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", ""))
                    .addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "referer", ""));
videoView.videoInfo(videoInfo).getPlayer().start();`

**Comment by tcking** [comment]
.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "referer: xxx\r\nuser-agent: okhttp\r\n"))

**Comment by techcalibrator** [comment]
Thanks @tcking
