### ISSUE TITLE
Using custom headers while set Video URI

### ISSUE THREAD

**Issue by yunusmete** [tcking/GiraffePlayer2#155]
Hi everyone,

I want to set user-agent while set video URI and found that this feature is implemented in GiraffePlayer like that.

>     /**
     * Sets video URI using specific headers.
     *
     * @param uri     the URI of the video.
     * @param headers the headers for the URI request.
     *                Note that the cross domain redirection is allowed by default, but that can be
     *                changed with key/value pairs through the headers parameter with
     *                "android-allow-cross-domain-redirect" as the key and "0" or "1" as the value
     *                to disallow or allow cross domain redirection.
     */
    private GiraffePlayer setVideoURI(Uri uri, Map<String, String> headers) throws IOException {
        this.uri = uri;
        this.headers.clear();
        this.headers.putAll(headers);
        seekWhenPrepared = 0;
        return this;
}

Unfortunately, there is no public API to use. Is there any way to achieve this?
Thanks

**Comment by tcking** [comment]
Hi,you can set headers like this:
```` java

videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "Connection: keep-alive\r\nuser-agent: okhttp\r\n"))

```
every header KV pairs separate by `\r\n`

**Comment by yunusmete** [comment]
Thanks @tcking, closing the issue.
