### ISSUE TITLE
Can I set User Agent?

### ISSUE THREAD

**Issue by techcalibrator** [tcking/GiraffePlayer2#17]

**Comment by Tulga** [comment]
videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "User-Agent: Mozilla/5.0... \r\n"))

OR 

videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user_agent", "User-Agent: Mozilla/5.0... \r\n"))

OR 

videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "user-agent", "User-Agent: Mozilla/5.0... \r\n"))
