### ISSUE TITLE
How to stop "player downloading" screen from Player ? 

### ISSUE THREAD

**Issue by prakashmp** [tcking/GiraffePlayer2#186]
When i open my video for the first time am getting "player downloading" screen with percentage. i want stop that screen and i need to open video directly.could you please suggest some solution.

Player version : implementation 'com.github.tcking:giraffeplayer2:0.1.25-full'

**Comment by tcking** [comment]
The decoder should be added to the build.gradle:
``` 
implementation "com.github.tcking:ijkplayer-armv7a:0.1.25-full"
implementation "com.github.tcking:ijkplayer-arm64:0.1.25-full"
```

**Comment by prakashmp** [comment]
i need to add this 3 version in my build.gradle am correct ? 
implementation 'com.github.tcking:giraffeplayer2:0.1.25-full'
implementation "com.github.tcking:ijkplayer-armv7a:0.1.25-full"
implementation "com.github.tcking:ijkplayer-arm64:0.1.25-full"
