### ISSUE TITLE
video aspect ratio not working properly

### ISSUE THREAD

**Issue by Tulga** [tcking/GiraffePlayer2#21]
when i set video aspect ratio to 16:9, its not working.

screenshot: 
https://ibb.co/i7e59m

**Comment by Tulga** [comment]
screen size: 1920x1080
android: 5.0.2 
api level: 21
cpu: armv7

**Comment by tcking** [comment]
will fix in next version

**Comment by tcking** [comment]
or u can pull from github to get `GiraffePlayer` , the latest commit fixed the issue

**Comment by tcking** [comment]
try this version: `compile 'com.github.tcking:giraffeplayer2:0.1.12'`

**Comment by Tulga** [comment]
tnk u 😊
