### ISSUE TITLE
Replay not working

### ISSUE THREAD

**Issue by prudhvicoder** [tcking/GiraffePlayer2#23]
I'm playing RTMP URL, after the video completion, when I click re-play button, the player is not replaying the video.

**Comment by tcking** [comment]
can u give the url ?

**Comment by prudhvicoder** [comment]
This is the URL I'm trying to play
rtmp://streamtube.streamhash.com:1935/vodst2/8a7948b4db40f4c766278f2dce83792f1ad31d1b.mp4

**Comment by tcking** [comment]
it seems the seek action does not work,but there is another way to fix the promble
```
videoView.setPlayerListener(new DefaultPlayerListener() {
            @Override
            public void onCompletion(GiraffePlayer giraffePlayer) {
                giraffePlayer.release();
            }
        });
```
this code will release the player when completion，and create a new player when restart playing

**Comment by prudhvicoder** [comment]
Thanks it works..!!
