### ISSUE TITLE
: FATAL EXCEPTION: GiraffePlayerInternal:Handler 

### ISSUE THREAD

**Issue by anupkunwar123** [tcking/GiraffePlayer2#24]
Please help i am getting the following error
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ekantipur.ktv-1/base.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.ekantipur.ktv-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.ekantipur.ktv-1/lib/arm64, /data/app/com.ekantipur.ktv-1/base.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.ekantipur.ktv-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

**Comment by tcking** [comment]
two ways to fix the problem:
add dependency: `compile 'com.github.tcking:ijkplayer-arm64:0.8.4'`
or
add abiFilters 'armlib' to you build file , please read [How to use 32-bit native libraries on 64-bit Android device
](https://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libraries-on-64-bit-android-device)

**Comment by anupkunwar123** [comment]
Thank you for the help. Problem resolved
