### ISSUE TITLE
Scale Gesture ( pinch zoom video feature  ) 

### ISSUE THREAD

**Issue by ShaBax** [tcking/GiraffePlayer2#25]
Hi 
I tried to implement ScaleGesture Detector in video view but with video, other views are also zooming. 
As media controller is attached with videoView and I'm unable to extract the video view part (where video actually plays) so that I can zoom in and zoom out the only video without changing the size of other views (seekbar and button etc).
Sorry for my bad explanation: all I want is to implement zoom in and zoom out like other gestures.
Please tell me how can I do that? Thank you

**Comment by tcking** [comment]
what you find is the `ScalableTextureView`,the view id is `R.id.player_display`

**Comment by ShaBax** [comment]
Thank you for response :) 
Now  I'm using this View like this.  
`           GiraffePlayer player = videoView.getPlayer();
            scalableTextureView=player.getCurrentDisplay();
            scalableTextureView.setScaleY(scale);
            scalableTextureView.setScaleX(scale);`
Am i  doing this in right way?

**Comment by tcking** [comment]
if still have questions,reopen it please

**Comment by ShaBax** [comment]
Thank you problem is solved :)
