### ISSUE TITLE
No thumbnail option

### ISSUE THREAD

**Issue by santhoshrao519** [tcking/GiraffePlayer2#27]
Hey firstly thanks a ton for providing such a wonderful library.
I would like to know whether it supports thumbnail of video in list.
Please do share your thoughts

**Comment by tcking** [comment]
videoView.getCoverView() is just a ImageView as thumbnail  and you can load image by your image load library

**Comment by santhoshrao519** [comment]
Thanks for the reply, can you please brief the getCoverView() in detail?

**Comment by tcking** [comment]
you can have a look at VideoAdapter.onBindViewHolder,it just a blank imageView,or you can add your ImageView as thumbnail in your item view

**Comment by santhoshrao519** [comment]
How do i pass an imageview in getcoverview()? will it support any parameter?

**Comment by tcking** [comment]
it a exits imageview,you can load image from local or url by other iamge load lib,eg:glide

**Comment by santhoshrao519** [comment]
I'm able to load local image but it's not showing play icon on
imageview..how can I achieve this

**Comment by tcking** [comment]
`Glide.with(videoView.getContext()).load("image url").into(videoView.getCoverView())`

**Comment by santhoshrao519** [comment]
I am able to load sample image from url, but my goal is to load a thumbnail(frame) of the video into videoview as preview image. How can i achieve this?
Please help out

**Comment by santhoshrao519** [comment]
I have used following code too

        Glide.with(feedListRowHolder.videoView.getContext()).load(APIConfig.URL_VIDEOLOC+feedItem.getVideoFile()).into(feedListRowHolder.videoView.getCoverView());

**Comment by santhoshrao519** [comment]
I've used following code

  BitmapPool bitmapPool = Glide.get(context).getBitmapPool();
        FileDescriptorBitmapDecoder decoder = new FileDescriptorBitmapDecoder(
                new VideoBitmapDecoder(50),
                bitmapPool,
                DecodeFormat.PREFER_ARGB_8888);

  Glide.with(context)
                .load(APIConfig.URL_VIDEOLOC+feedItem.getVideoFile())
                .asBitmap()
                .videoDecoder(decoder)
                .into(feedListRowHolder.videoView.getCoverView());

**Comment by Vikramsinh** [comment]
Can I use videoView.getCoverView().setBackground(mydrawable) ?

**Comment by tcking** [comment]
I just release 0.1.13, this version will get current video frame for cover when player is released (have a look add `DefaultMediaController.onRelease`),you can do anything on videoView.getCoverView(),it just a image view witch will gone while player is playing and visible while player is release

**Comment by tcking** [comment]
but it is hight cost if you want get a frame from video url as a cover (in list every player need to init and start buffering ), i do't think is a good idea

**Comment by santhoshrao519** [comment]
Guys, who ever need to show video thumbnail in their app, can use following code

   long interval = 5000 * 1000;
        RequestOptions options = new RequestOptions().frame(interval);
        Glide.with(context).asBitmap()
                .load(APIConfig.URL_VIDEOLOC+feedItem.getVideoFile())
                .apply(options)
                .into(feedListRowHolder.videoView.getCoverView());

Make sure you should use glide 4.5.0 gradle dependency..
Cheers

**Comment by santhoshrao519** [comment]
Hello @tcking ,
I'm calling videoView.getPlayer().toggleFullScreen(); to show video in full screen, but app is turning into landscape mode.
I'm not getting as exactly shown in demo gif

**Comment by tcking** [comment]
call `videoView.getVideoInfo().setPortraitWhenFullScreen(false)` first or you can set a global configuration when you app init: `PlayerManager.getInstance().getDefaultVideoInfo().setPortraitWhenFullScreen(false)`

**Comment by santhoshrao519** [comment]
Many Thanks for helping.. 👍
