### ISSUE TITLE
Full screen view having issue of Stretch

### ISSUE THREAD

**Issue by prudhvicoder** [tcking/GiraffePlayer2#28]
When I toggle my fullscreen without starting the video the full-screen view has a half video screen and a half control screen (in your demo app also you can see). How to fix this? And after completion of the video when I touch the seek bar it was showing in the middle (got stuck there) can I fix this? Maybe disabling the control after completion of the video also nice. Thank you in advance for creating such a wonderful library.!!

**Comment by tcking** [comment]
1. toggle fullscreen without starting the video the full-screen view has a half video screen and a half control screen -- is a bug, i fix the issue and push it
2.after completion of the video when I touch the seek bar it was showing in the middle -- I can't reproduce the problem,but you can do anything by set a `PlayerListener`,eg:

```
videoView.setPlayerListener(new DefaultPlayerListener() {

            @Override
            public void onStart(GiraffePlayer giraffePlayer) {
                $.id(R.id.app_video_seekBar).enabled(true);
            }

            @Override
            public void onCompletion(GiraffePlayer giraffePlayer) {
                $.id(R.id.app_video_seekBar).enabled(false);
            }
        });

```
