### ISSUE TITLE
HLS over the HTTPS Not working

### ISSUE THREAD

**Issue by nowfalsalahudeen** [tcking/GiraffePlayer2#29]
HLS over the HTTPS not working..any fix for that

https://jiotvweb.cdn.jio.com/jiotv.live.cdn.jio.com/Kairali_People_TV/Kairali_People_TV_800.m3u8?jct=3-SD3gYlLpcumY9XkgCFfA&pxe=1536692387&st=AQIC5wM2LY4SfcyZSshzplFrL13coOHl06FFURGPbuKWBYY.*AAJTSQACMDIAAlNLABI1OTA5Mzg0NTYxMTk1MDQ3MjYAAlMxAAIxNQ..*

sample link

**Comment by tcking** [comment]
the server return:HTTP error 406 Not Acceptable, the server may need some parameters

**Comment by nowfalsalahudeen** [comment]
but this link play in mx player
 copy that full link including the last ..* nd play
