### ISSUE TITLE
HLS  video not working

### ISSUE THREAD

**Issue by Tepehan** [tcking/GiraffePlayer2#3]
I got error like "Server returned 4XX Client Error, but not one of 40{0,1,3,4}"
This is the my url 
https://soledge20.dogannet.tv/S10/HLS_VOD/151461_90af/index.m3u8?key=0b6d42aca8d0dbdfb3d6cc9633150c8b&app=com.kanald&min=0&max=1250%22; 
I have tried many times but not working

**Comment by tcking** [comment]
server must return 200 not others,there are something wrong with the server or your request parameters, no player can playing with this url

**Comment by mekin** [comment]
There are no something wrong with the server I think that It is not working properly

**Comment by Tulga** [comment]
server should return 200 status code.

https://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by mekin** [comment]
I think you should not know  anything about software
I declared the link  above. And  if you try click it  you will see how it works so please do not comment if you dont have knowledge enough

**Comment by Tulga** [comment]
hey calm down, i think ur server's checking user-agent. 

check out this screenshots:
https://ibb.co/b2cAs6
https://ibb.co/goaVs6

solution add user agent option, not tested 
videoInfo.addOption(Option.create(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "headers", "User-Agent: Mozilla/5.0... \r\n")) etc..

**Comment by Tulga** [comment]
i think u still dont know how to works, some web servers. U should learn more.

**Comment by Tulga** [comment]
list of avalaible options

https://ffmpeg.org/ffmpeg-protocols.html#http
