### ISSUE TITLE
Override onbackpressed when fullscreen videoview

### ISSUE THREAD

**Issue by nowfalsalahudeen** [tcking/GiraffePlayer2#30]
onbackpressed pressed finish the current videoview holding activity. how can i override that same as videoview back arrow

**Comment by tcking** [comment]
add this code in your activity,take a look at demo project `BasePlayerActivity` 
```
@Override
    public void onBackPressed() {
        if (PlayerManager.getInstance().onBackPressed()) {
            return;
        }
        super.onBackPressed();
    }
```
