### ISSUE TITLE
关于播放屏幕不能常亮的问题

### ISSUE THREAD

**Issue by Lyang166** [tcking/GiraffePlayer2#31]
1：我在GiraffePlayer类的构造方法里面的handler中设置videoView.setKeepScreenOn(true);方法，但是播放完毕之后再重新播放会出现线程Exception
2：在activity中调用mVideoView.setVideoPath(url).getPlayer().start();，GiraffePlayer的start方法和handler会重复调用好几遍，也不知道是什么情况

**Comment by tcking** [comment]
贴日志看看

**Comment by Lyang166** [comment]
01-09 10:56:31.322 6862-6862/com.yll.dianyingtaotao D/qqqqq: new ; GiraffePlayer
01-09 10:56:31.323 6862-6862/com.yll.dianyingtaotao D/qqqqq: GiraffePlayer start
01-09 10:56:31.327 6862-6862/com.yll.dianyingtaotao D/qqqqq: GiraffePlayer start
01-09 10:56:31.560 6862-7056/com.yll.dianyingtaotao D/qqqqq: GiraffePlayer handler MSG_CTRL_PLAYING
这就是日志，关键还是屏幕不能常亮~

**Comment by tcking** [comment]
目前是采用`TextureView`来调用`IMediaPlayer.setSurface`,是不支持`setScreenOnWhilePlaying`的，不过可以通过这种方式来实现播放时常亮

```
videoView.setPlayerListener(new DefaultPlayerListener() {
            @Override
            public void onStart(GiraffePlayer giraffePlayer) {
                getActivity().getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }

            @Override
            public void onCompletion(GiraffePlayer giraffePlayer) {
                getActivity().getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }

            @Override
            public void onPause(GiraffePlayer giraffePlayer) {
                getActivity().getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
            }

            @Override
            public boolean onError(GiraffePlayer giraffePlayer, int what, int extra) {
                getActivity().getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
                return false;
            }
        });
```

**Comment by tcking** [comment]
0.1.13版本已经处理了，不需要手动处理了
