### ISSUE TITLE
recyclerView中，切换到下一个视频，上一个播放没有显示图片背景

### ISSUE THREAD

**Issue by lzj509649444** [tcking/GiraffePlayer2#32]
<img width="345" alt="2018-01-10 14 32 13" src="https://user-images.githubusercontent.com/1787221/34758798-750a5ede-f613-11e7-9348-a171f21f7163.png">

**Comment by tcking** [comment]
因为缩略图的app_video_cover在最下面，被盖住了，当时的想法只是弄个最简单的缩略图做个例子，视频停止时有的缩略图可能采用单独的图片，有的可能使用视频当时的画面，缩略图的这个逻辑应该app自身根据需要自己来处理

**Comment by tcking** [comment]
开始说法有误，应该是gone掉了，这里可以优化一下

**Comment by tcking** [comment]
这个问题fix了，pull最新代码或者更新到0.1.13

**Comment by lzj509649444** [comment]
@tcking 发现了3个bug
1. recyclerview中切换前面几个播放的视频，后面的视频封面也变成了暂停的状态
2. 切换暂停后的视频，有时候封面没有center crop，有时候是对的，我用的glide centerCropTransform
![wechatimg819](https://user-images.githubusercontent.com/1787221/34916624-3185b0a8-f976-11e7-99ea-623b8edd127d.jpeg)
3. 切换的过程中，有时候不显示封面，分两种情况（1. 有列表滚动，出现的概率大些 2.没有列表滚动，有时候会出现）
