### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nowfalsalahudeen** [tcking/GiraffePlayer2#33]
E/IJKMEDIA: https://origin-api-dhtv.dailyhunt.in/v2/item/yupptvredirect/262/master.m3u8: Server returned 403 Forbidden (access denied)

but this link perfectly working in exoplayer2 and all other players. and https link also not playing

**Comment by tcking** [comment]
access denied,the server need authentication parameters

**Comment by nowfalsalahudeen** [comment]
but its working in exoplayer2 without any parameters.. thats why i asked u

**Comment by tcking** [comment]
use charles to find the diff of the request,include the parameters and headers, btw I can't play the url with VLC

**Comment by tcking** [comment]
if still have questions,reopen it please
