### ISSUE TITLE
Not issue : How to get click event of full screen toggle ?

### ISSUE THREAD

**Issue by Vikramsinh** [tcking/GiraffePlayer2#34]
I need to open the current video in full screen mode on click on full-screen toggle. As like GiraffePlayer.DISPLAY_FULL_WINDOW.
Thanks in advance!!

**Comment by tcking** [comment]
if you want to get full screen event,override the callback method `onDisplayModelChange`:
```
videoView.setPlayerListener(new DefaultPlayerListener() {
            @Override
            public void onDisplayModelChange(int oldModel, int newModel) {
                if (newModel == GiraffePlayer.DISPLAY_FULL_WINDOW) {
                    //do something
                }
            }
        });
```
if you open video in full screen mode,just call
```
videoView.getPlayer().setDisplayModel(GiraffePlayer. DISPLAY_FULL_WINDOW)
```

**Comment by Vikramsinh** [comment]
Thanks. But I have one problem right now, i.e. after opening in full screen, controls are visible behind the Android bottom buttons?

**Comment by tcking** [comment]
pull from github,it has been fixed(but not release a new version)

**Comment by Vikramsinh** [comment]
Thanks. But please release the new version with this bug fix. Thanks in advance.

**Comment by Vikramsinh** [comment]
I can't access controller when the video is in fullscreen?

**Comment by tcking** [comment]
yes you can

**Comment by tcking** [comment]
if still have questions,reopen it please
