### ISSUE TITLE
On full screen, Controls are hiding behind the android buttons.

### ISSUE THREAD

**Issue by Vikramsinh** [tcking/GiraffePlayer2#35]
![screenshot_20180110-194135](https://user-images.githubusercontent.com/10560800/34776955-a4d6f9ee-f63e-11e7-95e4-d3b541d100dc.png)

on full screen, it looks like above screen. Controls are hiding behind android buttons. 
How to solve?

**Comment by tcking** [comment]
please remove line 64 in UIHelper.java https://github.com/tcking/GiraffePlayer2/blob/master/giraffeplayer2/src/main/java/tcking/github/com/giraffeplayer2/UIHelper.java#L64
