### ISSUE TITLE
How to set loop video player?

### ISSUE THREAD

**Issue by kimnamcham** [tcking/GiraffePlayer2#37]
How can i set video player looping? Thanks!

**Comment by tcking** [comment]
I will add looping surpport next version,you can add `mediaPlayer.setLooping(true);` in `GiraffePlayer.init`,or add a listener,eg:
```
videoView.setPlayerListener(new DefaultPlayerListener() {
            @Override
            public void onCompletion(GiraffePlayer giraffePlayer) {
                giraffePlayer.start();
            }
        });
``

**Comment by tcking** [comment]
new version can call `videoView.getVideoInfo().setLooping(true)`
