### ISSUE TITLE
recycleview中，视频切换播放，封面显示bug

### ISSUE THREAD

**Issue by lzj509649444** [tcking/GiraffePlayer2#38]
发现了3个bug
1. recyclerview中切换前面几个播放的视频，其他的视频封面也变成了暂停的状态
<img width="345" alt="2018-01-14 22 13 29" src="https://user-images.githubusercontent.com/1787221/34916759-3b0b0b94-f978-11e7-9988-1a8c83655231.png">

2. 切换暂停后的视频，有时候封面没有center crop，有时候是对的，我用的glide centerCropTransform
```
videoPlayer = (VideoPlayer) itemView.findViewById(R.id.videoPlayer);
videoPlayer.getVideoInfo().setAspectRatio(VideoInfo.AR_ASPECT_FILL_PARENT);
```
![wechatimg819](https://user-images.githubusercontent.com/1787221/34916624-3185b0a8-f976-11e7-99ea-623b8edd127d.jpeg)
3. 切换的过程中，有时候不显示封面，分两种情况（1. 有列表滚动，出现的概率大些 2.没有列表滚动，有时候会出现）

**Comment by tcking** [comment]
问题1目前就是这样设计的，播放其他视频的时候，上一个视频会截取当时播放时的画面作为封面，这块逻辑在`DefaultMediaController.onRelease`中，如果想用之前的封面图片，可以把if里的注释掉
问题2目前封面的scaleType为fitCenter，并没有根据video的aspectRatio变化，这里下个版本可以优化一下
问题3，由于采用1的逻辑，在视频画面还没出来的时候截的图就是黑的，可能导致这个问题

**Comment by tcking** [comment]
刚发了0.1.14版本，问题1目前采用配置的方式，可以通过调用videoInfo.setCurrentPlayer(false)来关闭（也可以通过PlayerManager.getInstance().getDefaultVideoInfo().setCurrentPlayer(false)全局关闭），问题2现在根据视频aspectRatio来修改scaleType

**Comment by tcking** [comment]
之前描述的错了，应该是：`videoInfo.setCurrentVideoAsCover(false)`
