### ISSUE TITLE
DEMO 中设置播放器为AndroidMediaPlayer会报错

### ISSUE THREAD

**Issue by lqfsharks** [tcking/GiraffePlayer2#4]
第一步，设置播放器为AndroidMediaPlayer
videoView.getVideoInfo().setPlayerImpl(VideoInfo.PLAYER_IMPL_SYSTEM);

第二步，开始播放后会收到onError回调（在GiraffePlayer类中）
mediaPlayer.setOnErrorListener(new IMediaPlayer.OnErrorListener() {
            @Override
            public boolean onError(IMediaPlayer iMediaPlayer, int what, int extra) {
              
            }
        });
onError参数为 what:-38， extra：0

如果采用默认实现即IjkMediaPlayer则没有问题，请问这个问题是什么原因，怎么解决

**Comment by tcking** [comment]
目前有个问题：player还未初始化时调用了`getDuration`会导致这个错误，但是这个错误不影响正常的播放，之后将会修复这个问题

**Comment by tcking** [comment]
`0.1.7`版本已经修复这个问题

`compile 'com.github.tcking:giraffeplayer2:0.1.7'`
