### ISSUE TITLE
包含ijkplayer的库文件在哪里,没找到

### ISSUE THREAD

**Issue by luckyer** [tcking/GiraffePlayer2#40]
RT

**Comment by luckyer** [comment]
giraffeplayer上个版本里面还有个ijkplayer-java的目录的,这个版本是换成用jar文件了么,请问这个文件在哪里.

**Comment by tcking** [comment]
看下giraffeplayer2/build.gradle文件，从这里引入的，没有直接引用ijkplayer的aar，修改了ijkplayer的部分代码，重新编译的 https://github.com/tcking/ijkplayer

**Comment by luckyer** [comment]
@tcking   看了下代码,    
public IjkMediaPlayer(Looper looper) {
        this(sLocalLibLoader,looper);
    }
上面这个接口修改了没有更新到上面的链接中么

**Comment by tcking** [comment]
更新了，应该是dev分支

**Comment by luckyer** [comment]
@tcking 感谢
