### ISSUE TITLE
Video seek not working sometimes

### ISSUE THREAD

**Issue by Tulga** [tcking/GiraffePlayer2#42]
![screenshot_2018-01-23-04-35-34](https://user-images.githubusercontent.com/1684096/35354010-d9a0597c-0183-11e8-9853-35255324e403.png)
![screenshot_2018-01-25-03-43-30](https://user-images.githubusercontent.com/1684096/35354011-d9dac0d0-0183-11e8-85a9-35b1224e0825.png)

its giving negative seek number and not seekeble

**Comment by tcking** [comment]
can you give the url that i can test the case?

**Comment by Tulga** [comment]
http://103.60.97.10/vod/_definst_/mp4:tv/mobile/edu.stream-2018-01-21-22-55-00.mp4/playlist.m3u8?t=7241ee616482a60192d3217fd1c04578

**Comment by tcking** [comment]
this bug fix  @`0.1.16` please update version or pull

**Comment by Tulga** [comment]
tnk you, u re the best

**Comment by son2017** [comment]
@tcking the seek is not working some time please make sure its working fine.
