### ISSUE TITLE
Remove the bottom bar?

### ISSUE THREAD

**Issue by shinayser** [tcking/GiraffePlayer2#48]
Hello!
I dig through the VideoView but could not find a way to remove the bottom bar/MediaController (the one with the play/stop button and seekbar).
There is any way to do that I am missing?

**Comment by tcking** [comment]
all media controller's ui handle in `DefaultMediaController.java`, have a look at this file,if you want remove all the contronller see https://github.com/tcking/GiraffePlayer2/issues/9

**Comment by szymanskip** [comment]
Is there a reason why there's no way to swap `MediaController` implementation in `VideoView`?
So currently the only solution to this issue is to fork the library?

**Comment by amanzan** [comment]
There should be an option to hide controls

**Comment by tcking** [comment]
it will create a MediaController at runtime without fork the lib
