### ISSUE TITLE
Trouble opening an encrypted file

### ISSUE THREAD

**Issue by pattarapol15** [tcking/GiraffePlayer2#5]
I have trouble opening an encrypted file. To open a file. VideoInfo.PLAYER_IMPL_IJK Please help

*ps.Probably openssl.

![screen shot 2017-10-17 at 10 15 58 am](https://user-images.githubusercontent.com/8523961/31647602-68ad8cba-b333-11e7-8afe-ecaf8496fefa.png)

**Comment by tcking** [comment]
can `VLC` play your url?

**Comment by pattarapol15** [comment]
VLC can play the link.

**Comment by tcking** [comment]
GiraffePlayer2 compile with openssl,but your url is http not https, can u give me a url the i can access？

**Comment by pattarapol15** [comment]
I try http://playertest.longtailvideo.com/adaptive/oceans_aes/oceans_aes.m3u8 
Have a single problem

**Comment by tcking** [comment]
the problem was solved by recompile ijkplayer with `module-default.sh`,but there are something wrong with my network that i can't push so to jcenter,I will push it later when I get good network

**Comment by pattarapol15** [comment]
Thank you very much for the help.

**Comment by tcking** [comment]
new aar has been publish to jcenter,using this version:
`compile 'com.github.tcking:giraffeplayer2:0.1.8-full'`

**Comment by pattarapol15** [comment]
I have already tested and it works fine. Thank You
