### ISSUE TITLE
thumbnail video

### ISSUE THREAD

**Issue by afaideen** [tcking/GiraffePlayer2#50]
Hi,
I'd like to know after finished downloading video file then how to firstly display the thumbnail. This is because the videoview looks nothing and black before playing the video.

**Comment by tcking** [comment]
`MediaMetadataRetrieve` can do this

**Comment by tcking** [comment]
player not do like this because this is high cost, especially in a list, this is better do in server side and provide  a image as thumbnail to client apps

**Comment by afaideen** [comment]
thanks
