### ISSUE TITLE
Gradle of lazyload seem to be not working

### ISSUE THREAD

**Issue by ekimual** [tcking/GiraffePlayer2#52]
`compile 'com.github.tcking:giraffeplayer2:0.1.18-lazyload' `

Seems not to work but others were fine. ( I have jcenter libraries btw )

**Comment by tcking** [comment]
I will check this after my holiday

**Comment by tcking** [comment]
please using:`compile 'com.github.tcking:giraffeplayer2:0.1.18-lazyLoad'`, the letter L is upper case

**Comment by ekimual** [comment]
This means it will provide the appropriate native architecture SO files when the app is running right?

**Comment by tcking** [comment]
yes,It will downloading the appropriate native architecture SO files when player first play

**Comment by ekimual** [comment]
Only on first play right? Nice one. Thanks!
