### ISSUE TITLE
大神网络切换出现的bug

### ISSUE THREAD

**Issue by liana101** [tcking/GiraffePlayer2#58]
断开wifi，移动4G上网，视频播放停止，点击播放视频无法继续播放
log 如下：
02-28 08:57:47.889 9928-9928/com.github.tcking.giraffeplayer.example I/tv.danmaku.ijk.media.player.IjkMediaPlayer: Info: MEDIA_INFO_VIDEO_RENDERING_START
02-28 08:57:50.725 9928-10021/com.github.tcking.giraffeplayer.example E/IJKMEDIA: Hit dns cache but connect fail hostname = live.hkstv.hk.lxdns.com, ip = 
02-28 08:58:09.493 9928-10021/com.github.tcking.giraffeplayer.example E/IJKMEDIA: http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8: error while seeking
02-28 08:58:10.255 9928-10021/com.github.tcking.giraffeplayer.example E/IJKMEDIA: http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8: error while seeking

然后，关闭屏幕，在开启屏幕，视频能继续播放。
还有一个问题，是播放其他视频mp4文件，断开网络，视频播放停止，连上网络，点击播放时，播放有声音但是从头开始，但画面不动。

**Comment by tcking** [comment]
可以通过如下方式解决：
```
videoView.setPlayerListener(new DefaultPlayerListener() {
            @Override
            public void onCompletion(GiraffePlayer giraffePlayer) {
                giraffePlayer.release();
            }
        });
```
