### ISSUE TITLE
Right to Left support

### ISSUE THREAD

**Issue by saefbadwan** [tcking/GiraffePlayer2#59]
you just need to set gravity for views , or you could add a separate layouts 
![screenshot_2018-02-28-11-26-47](https://user-images.githubusercontent.com/29406317/36780020-7ed585e6-1c7a-11e8-80f0-e37e09507918.png)

**Comment by tcking** [comment]
I have push the update to support RTL,please pull from the update (not release a new version)
![image](https://user-images.githubusercontent.com/2508474/36884962-18c3f656-1e1f-11e8-8039-346a91c654a8.png)

**Comment by tcking** [comment]
version 0.1.19 support RTL
