### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Looper;)V in class Ltv/danmaku/ijk/media/player/IjkMediaPlayer; or its super classes (declaration of 'tv.danmaku.ijk.media.player.IjkMediaPlayer' appears in /data/app/smm.giraffe-2/base.apk)

### ISSUE THREAD

**Issue by smmhub** [tcking/GiraffePlayer2#60]
Trying to start video (by calling start method or pressing play button on videoview ) 

java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Looper;)V in class Ltv/danmaku/ijk/media/player/IjkMediaPlayer; or its super classes (declaration of 'tv.danmaku.ijk.media.player.IjkMediaPlayer' appears in /data/app/smm.giraffe-2/base.apk)
	at tcking.github.com.giraffeplayer2.GiraffePlayer.createMediaPlayer(GiraffePlayer.java:441)
	at tcking.github.com.giraffeplayer2.GiraffePlayer.init(GiraffePlayer.java:391)
	at tcking.github.com.giraffeplayer2.GiraffePlayer.access$600(GiraffePlayer.java:54)
	at tcking.github.com.giraffeplayer2.GiraffePlayer$1.handleMessage(GiraffePlayer.java:158)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tcking** [comment]
I have modify the ijkplayer-java code ,so please del the ijkplaer-java dependency `compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.4` (or other version)

**Comment by smmhub** [comment]
Thanks for your reply .
Should I get this one https://github.com/tcking/ijkplayer ?

**Comment by smmhub** [comment]
Is this good ?

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.github.tcking:viewquery:1.6'
    compile 'com.android.support:appcompat-v7:25.3.1'
    
    compile 'com.github.tcking:giraffeplayer2:0.1.18-full'
    if ("" == bType) {
        compile "com.github.tcking:ijkplayer-armv7a:${ijkVersion}"
    } else if ("full" == bType) {
        compile "com.github.tcking:ijkplayer-armv7a:${ijkVersion}-full"
    }
}
apply from: new File(projectDir, "gradle-on-demand.gradle")

**Comment by tcking** [comment]
is the demo occur the error or your project?

**Comment by smmhub** [comment]
demo works properly
but my project a wrapper for B4A language does not .
If I  remove ijkplayer-java depenency , then application crashes with the following error 

java.lang.NoClassDefFoundError: Failed resolution of: Ltv/danmaku/ijk/media/player/IjkMediaPlayer;
	at tcking.github.com.giraffeplayer2.GiraffePlayer.createMediaPlayer(GiraffePlayer.java:441)
	at tcking.github.com.giraffeplayer2.GiraffePlayer.init(GiraffePlayer.java:391)
	at tcking.github.com.giraffeplayer2.GiraffePlayer.access$600(GiraffePlayer.java:54)
	at tcking.github.com.giraffeplayer2.GiraffePlayer$1.handleMessage(GiraffePlayer.java:158)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:150)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.IjkMediaPlayer" on path: DexPathList[[zip file "/data/app/smm.giraffe-1/base.apk"],nativeLibraryDirectories=[/data/app/smm.giraffe-1/lib/arm, /data/app/smm.giraffe-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 7 more
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.IjkMediaPlayer" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 8 more
		Suppressed: java.lang.ClassNotFoundException: tv.danmaku.ijk.media.player.IjkMediaPlayer
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 9 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
** Activity (main) Pause, UserClosed = true **


Can you please tell all jars and aar s files required ?

**Comment by tcking** [comment]
player it self `compile "com.github.tcking:ijkplayer-java:0.8.4"` (rather than  `compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'`)，try to add `compile "com.github.tcking:ijkplayer-java:0.8.4"`

**Comment by smmhub** [comment]
But com.github.tcking:ijkplayer-java:0.8.4 is still not included inside giraffeplayer2-release.aar

**Comment by tcking** [comment]
in theory，you need not care for the player's dependencies,the gradle will auto handle that, just like the demo's build.gradle,the only dependence you should add is `compile 'com.github.tcking:giraffeplayer2:0.1.18` (or compile 'com.github.tcking:giraffeplayer2:0.1.18-lazyload'), can you give the result for command:./gradlew app:dependencies

**Comment by smmhub** [comment]
`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\Users\smm\Desktop\0compilemylibs\GiraffePlayer2Z>gradlew app:dependencies
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --statu
s for details
Download https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle
-2.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.2/g
radle-core-2.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder/2.3.2/build
er-2.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint/25.3.2/lint-25.
3.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle-api/2.3.2/gr
adle-api-2.3.2.pom
Download https://jcenter.bintray.com/com/android/databinding/compilerCommon/2.3.
2/compilerCommon-2.3.2.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.2/progu
ard-gradle-5.3.2.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-parent/5.3.2/progu
ard-parent-5.3.2.pom
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.0.0/pro
tobuf-java-3.0.0.pom
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-parent/3.0.0/p
rotobuf-parent-3.0.0.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder-model/2.3.2
/builder-model-2.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/builder-test-api/2.
3.2/builder-test-api-2.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/sdklib/25.3.2/sdklib-25.3
.2.pom
Download https://jcenter.bintray.com/com/android/tools/sdk-common/25.3.2/sdk-com
mon-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/common/25.3.2/common-25.3
.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/manifest-merger/25.
3.2/manifest-merger-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.3.2/ddmlib
-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.13.0/jack
-api-0.13.0.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/protos/
25.3.2/protos-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/shared/
25.3.2/shared-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/analytics-library/tracker
/25.3.2/tracker-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.2/l
int-checks-25.3.2.pom
Download https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj
-4.6.1.pom
Download https://jcenter.bintray.com/com/android/databinding/baseLibrary/2.3.2/b
aseLibrary-2.3.2.pom
Download https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.2/proguar
d-base-5.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/2
5.3.2/layoutlib-api-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/dvlib/25.3.2/dvlib-25.3.2
.pom
Download https://jcenter.bintray.com/com/android/tools/repository/25.3.2/reposit
ory-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.3.2/lint
-api-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/external/com-intellij/uas
t/162.2228.14/uast-162.2228.14.pom
Download https://jcenter.bintray.com/com/android/tools/annotations/25.3.2/annota
tions-25.3.2.pom
Download https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle
-2.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.2/g
radle-core-2.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder/2.3.2/build
er-2.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint/25.3.2/lint-25.
3.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/gradle-api/2.3.2/gr
adle-api-2.3.2.jar
Download https://jcenter.bintray.com/com/android/databinding/compilerCommon/2.3.
2/compilerCommon-2.3.2.jar
Download https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.2/progu
ard-gradle-5.3.2.jar
Download https://jcenter.bintray.com/com/google/protobuf/protobuf-java/3.0.0/pro
tobuf-java-3.0.0.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder-model/2.3.2
/builder-model-2.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/builder-test-api/2.
3.2/builder-test-api-2.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/sdklib/25.3.2/sdklib-25.3
.2.jar
Download https://jcenter.bintray.com/com/android/tools/sdk-common/25.3.2/sdk-com
mon-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/common/25.3.2/common-25.3
.2.jar
Download https://jcenter.bintray.com/com/android/tools/build/manifest-merger/25.
3.2/manifest-merger-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.3.2/ddmlib
-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/jack/jack-api/0.13.0/jack
-api-0.13.0.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/protos/
25.3.2/protos-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/shared/
25.3.2/shared-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/analytics-library/tracker
/25.3.2/tracker-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint-checks/25.3.2/l
int-checks-25.3.2.jar
Download https://jcenter.bintray.com/org/eclipse/jdt/core/compiler/ecj/4.6.1/ecj
-4.6.1.jar
Download https://jcenter.bintray.com/com/android/databinding/baseLibrary/2.3.2/b
aseLibrary-2.3.2.jar
Download https://jcenter.bintray.com/net/sf/proguard/proguard-base/5.3.2/proguar
d-base-5.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/layoutlib/layoutlib-api/2
5.3.2/layoutlib-api-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/dvlib/25.3.2/dvlib-25.3.2
.jar
Download https://jcenter.bintray.com/com/android/tools/repository/25.3.2/reposit
ory-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/lint/lint-api/25.3.2/lint
-api-25.3.2.jar
Download https://jcenter.bintray.com/com/android/tools/external/com-intellij/uas
t/162.2228.14/uast-162.2228.14.jar
Download https://jcenter.bintray.com/com/android/tools/annotations/25.3.2/annota
tions-25.3.2.jar
WARNING [Project: :giraffeplayer2] Support for libraries with same package name
is deprecated and will be removed in a future release.

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'GiraffePlayer2Z'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 5 mins 38.796 secs

> IDLE
`

**Comment by smmhub** [comment]
Sorry : 
My application does not use gradle

**Comment by smmhub** [comment]
I want to know which .jars and/or aars files that the application requires and I will do the rest

**Comment by tcking** [comment]
compile "com.github.tcking:ijkplayer-java:0.8.4"
compile "com.github.tcking:ijkplayer-armv7a:0.8.4"

**Comment by smmhub** [comment]
+  com.github.tcking:giraffeplayer2:0.1.18-full ?

**Comment by smmhub** [comment]
I meant + com.github.tcking:giraffeplayer2:0.1.18-full

**Comment by tcking** [comment]
if you want full featrues:
```
compile "com.github.tcking:ijkplayer-java:0.8.4"
compile "com.github.tcking:ijkplayer-armv7a:0.8.4-full"
```
the ijkplayer-java is same,only so files is diff

**Comment by smmhub** [comment]
Sorry for asking too much 
Are com.github.tcking:ijkplayer-java:0.8.4, com.github.tcking:ijkplayer-armv7a:0.8.4-full and com.github.tcking:giraffeplayer2:0.1.18-full  the only aars required

**Comment by tcking** [comment]
```
com.github.tcking:viewquery:1.6
com.github.tcking:ijkplayer-java:0.8.4
com.github.tcking:ijkplayer-armv7a:0.8.4-full
com.android.support:appcompat-v7:25.3.1
```
all is here

**Comment by smmhub** [comment]
This one is not needed com.github.tcking:giraffeplayer2:0.1.18-full?

**Comment by tcking** [comment]
need it,the above is  com.github.tcking:giraffeplayer2:0.1.18-full dependencies

**Comment by smmhub** [comment]
Can you please check if these files are the required ?




[dependencie.zip](https://github.com/tcking/GiraffePlayer2/files/1779563/dependencie.zip)

**Comment by tcking** [comment]
lack of viewquery-1.6.aar ，why not using gradle？

**Comment by smmhub** [comment]
Sorry , viewquery is added as java source and compiled when compiling my wrapper .
The language I am developing wrapper for does not support gradle .

**Comment by smmhub** [comment]
Just in case , my wrapper library depends on those : 
"giraffeplayer2-release.aar","viewquery-release.aar","ijkplayer-java-release.aar","com.android.support:appcompat-v7"

**Comment by smmhub** [comment]
Whatever I do I always hit this error : 
java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Looper;)V in class Ltv/danmaku/ijk/media/player/IjkMediaPlayer; or its super classes (declaration of 'tv.danmaku.ijk.media.player.IjkMediaPlayer' appears in /data/app/smm.giraffe-1/base.apk)

**Comment by smmhub** [comment]
Should .so files be copied manually to a specific folder ?

**Comment by tcking** [comment]
the error is not related to so files, where are you download `ijkplayer-java-release.aar` ?,it should be download from `https://jcenter.bintray.com/com/github/tcking/ijkplayer-java/0.8.4/:ijkplayer-java-0.8.4.aar`

**Comment by smmhub** [comment]
Thank you very much .
I was compiling it on android studio but after downloading your aar , the crash has disappear .
Now downloading player 0% but it does not get started ( This seems another issue I will check it myself ) Thanks a lot for your support :)

**Comment by tcking** [comment]
to fix this error you need download from `https://jcenter.bintray.com/com/github/tcking/giraffeplayer2/0.1.18/:giraffeplayer2-0.1.18.aar` to replace the giraffeplayer2-release.aar

**Comment by smmhub** [comment]
Unfortunately it didn't fix downloading player 0% :(

**Comment by tcking** [comment]
download https://jcenter.bintray.com/com/github/tcking/ijkplayer-armv7a/0.8.4-full/:ijkplayer-armv7a-0.8.4-full.aar to your dependencies

**Comment by smmhub** [comment]
I have already downloaded it but later I realized I did not move .so files to their required directory .

Thanks a lot man , now it seems working properly :) 
You may close this issue at any time you want
