### ISSUE TITLE
GiraffePlayer.java:441: error: incompatible types: Looper cannot be converted to IjkLibLoader

### ISSUE THREAD

**Issue by smmhub** [tcking/GiraffePlayer2#61]
I tried to compile a library wrapper but I get this strange error 
GiraffePlayer.java:441: error: incompatible types: Looper cannot be converted to IjkLibLoader
        return new IjkMediaPlayer(Looper.getMainLooper());

**Comment by tcking** [comment]
this maybe the same as https://github.com/tcking/GiraffePlayer2/issues/60
