### ISSUE TITLE
怎么可以联系到作者想问你几个封装视频播放的问题

### ISSUE THREAD

**Issue by tianshaokai** [tcking/GiraffePlayer2#66]
我主要是想问一下 https://github.com/tcking/GiraffePlayer/blob/master/giraffeplayer/src/main/java/tcking/github/com/giraffeplayer/TextureRenderView.java 原来的库中设置了一些 ijkplayer 的surfaceview 参数，这个新库里 很少有这些设置，作者你能不能详细说一下呢

**Comment by tcking** [comment]
TextureView的回调都是需要调用的，只是没有在自定义的TextureView中，代码在`GiraffePlayer.bindDisplay()`中

**Comment by tcking** [comment]
目前没有 😢
