### ISSUE TITLE
Cannot be cast to VideoView 

### ISSUE THREAD

**Issue by mohamedebrahim96** [tcking/GiraffePlayer2#73]
i can't cast the VideoView like the image 
=========

![erwerwerwerwerwerwer](https://user-images.githubusercontent.com/16405013/37594551-337da066-2b7e-11e8-94f0-ce4a7d65f025.JPG)

and this is the error 
![wrwerewrer](https://user-images.githubusercontent.com/16405013/37594572-454506b8-2b7e-11e8-8c88-701ae63c24ab.JPG)

and this line in gradle 
 `implementation 'com.github.tcking:giraffeplayer2:0.1.19' `

and this is the XML 
```
<tcking.github.com.giraffeplayer2.VideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
```

**Comment by tcking** [comment]
the log is clear，is `tcking.github.com.giraffeplayer2.VideoView` not `android.widget.VideoView`,you declar your var as `android.widget.VideoView` but it should be `tcking.github.com.giraffeplayer2.VideoView`

**Comment by mohamedebrahim96** [comment]
does it support HLS videos ?

**Comment by tcking** [comment]
yes,you can try the demo
