### ISSUE TITLE
[Request] Exit full-screen when rotating the device.

### ISSUE THREAD

**Issue by bernaferrari** [tcking/GiraffePlayer2#82]
Hi, I think you could make GiraffePlayer2 a bit more like YouTube or Videoder app. On both of them, if you tap on the full-screen button, the video will get full-screen, but if you rotate the device back, it will exit full screen. On GiraffePlayer2, it is permanent.

**Comment by bilgehankalkan** [comment]
You can create custom OrientationEventListener to listen orientation changes. I'm using [this](https://stackoverflow.com/a/13844242) solution and manually managing orientation changes by this listeners responses.

**Comment by bernaferrari** [comment]
I thought this was a solved problem already, I was avoiding what you sent me at all costs, but I'll probably need to implement it. Thanks!
