### ISSUE TITLE
How to hide the controls

### ISSUE THREAD

**Issue by prudhvicoder** [tcking/GiraffePlayer2#9]
I don't need the control layout, I'm implementing a full-screen video view. I'm hiding the app_bottom_box visibility to GONE, but onTouchListener is activating the layout to be visible. How can I hide the control layout? Thanks in Advance.

**Comment by tcking** [comment]
you can del `initMediaController ()` in `init()` method  in file: [VideoView.java](https://github.com/tcking/GiraffePlayer2/blob/5bad114e961b7e2beb33d56bb39d48d83813ef57/giraffeplayer2/src/main/java/tcking/github/com/giraffeplayer2/VideoView.java#L81)

**Comment by prudhvicoder** [comment]
Thanks tcking
