### ISSUE TITLE
RTMP livestream timestamp

### ISSUE THREAD

**Issue by nayeemzen** [tcking/GiraffePlayer2#96]
Hi, is it possible to get the server timestamp from the RTMP stream? `getCurrentPosition()` only tells me about the local playback duration. I want to know the server timestamp which should be available in the RTMP headers.

This is because I want to synchronize my data to be displayed at the proper time on the livestream (The stream may be lagging a couple of seconds behind).

**Comment by tcking** [comment]
i don't think so,and the server time and local time also difference，i don't think this is a good selution to solve the problem

**Comment by nayeemzen** [comment]
How would you display content (e.g advertisement/annotation/subtitle) at certain points on the livestream?

**Comment by nayeemzen** [comment]
any suggestions @tcking ?
